[PagoPa-928] Enrolled EC
pagopa/pagopa-platform-authorizer pull request #5
Opened 2023-05-17 15:43 UTC by alessio-acitelli

#### List of Changes

- created a new function to return the enrolled EC 

#### Motivation and Context

- new feature

#### How Has This Been Tested?

manual and junit test

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-05-17 16:13 UTC, pasqualespica approved these changes
great 👍

2023-05-18 07:58 UTC, pasqualespica requested changes
All right, y'd add 
-  openapi spec
- local setting json for env vars
- change api base path
too

2023-05-18 07:58 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/authorizer/EnrolledEC.java
> +                    route = "api/ec/domain/{domain}",
`/organizations/domains/{domain}`

2023-05-18 09:22 UTC, alessio-acitelli commented on src/main/java/it/gov/pagopa/authorizer/EnrolledEC.java
> +        logger.log(Level.INFO, () -> String.format("The execution will end with an HTTP status code %d and duration time %d ms", HttpStatus.OK.value(), Duration.between(start, Instant.now()).toMillis
Done. In **java.util.logging.Logger** FINE is actually corresponding to DEBUG

2023-05-19 07:33 UTC, pasqualespica approved these changes
good 👍

2023-05-19 07:34 UTC, merged